FROM node:22-alpine
RUN npm install -g pnpm

WORKDIR /app
COPY . .
RUN pnpm install
RUN pnpm --filter @qimela/api db:generate

EXPOSE 3000
EXPOSE 9229

CMD ["pnpm", "--filter", "@qimela/api", "start:debug"]
